---
dependencies:
- name: "jenkins"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "0.10.37"
  condition: "jenkins-x-platform.jenkins.enabled,jenkins.enabled"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.111"
  alias: "expose"
  condition: "jenkins-x-platform.expose.enabled,expose.enabled"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.111"
  alias: "cleanup"
  condition: "jenkins-x-platform.cleanup.enabled,cleanup.enabled"
- name: "chartmuseum"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.1.5"
  condition: "jenkins-x-platform.chartmuseum.enabled,chartmuseum.enabled"
- name: "nexus"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "0.1.7"
  condition: "jenkins-x-platform.nexus.enabled,nexus.enabled"
- name: "heapster"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "0.3.2"
- name: "docker-registry"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "1.5.0"
  condition: "jenkins-x-platform.docker-registry.enabled,docker-registry.enabled"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  alias: "gcactivities"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  alias: "gcpods"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  alias: "gcpreviews"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  condition: "jenkins-x-platform.controllerbuild.enabled,controllerbuild.enabled"
  alias: "controllerbuild"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  condition: "jenkins-x-platform.controllerrole.enabled,controllerrole.enabled"
  alias: "controllerrole"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  condition: "jenkins-x-platform.controllerworkflow.enabled,controllerworkflow.enabled"
  alias: "controllerworkflow"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  condition: "jenkins-x-platform.controllerteam.enabled,controllerteam.enabled"
  alias: "controllerteam"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  condition: "jenkins-x-platform.controllercommitstatus.enabled,controllercommitstatus.enabled"
  alias: "controllercommitstatus"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.0.372"
  condition: "jenkins-x-platform.postinstalljob.enabled,postinstalljob.enabled"
  alias: "postinstalljob"
