dependencies:
- condition: jenkins-x-platform.jenkins.enabled,jenkins.enabled
  name: jenkins
  repository: http://chartmuseum.jenkins-x.io
  version: 0.10.37
- alias: jenkins-x-platform.expose.enabled,expose.enabled
  condition: expose.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- alias: cleanup
  condition: jenkins-x-platform.cleanup.enabled,cleanup.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- condition: jenkins-x-platform.chartmuseum.enabled,chartmuseum.enabled
  name: chartmuseum
  repository: http://chartmuseum.jenkins-x.io
  version: 1.1.5
- condition: jenkins-x-platform.nexus.enabled,nexus.enabled
  name: nexus
  repository: http://chartmuseum.jenkins-x.io
  version: 0.1.7
- name: heapster
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.3.2
- condition: jenkins-x-platform.docker-registry.enabled,docker-registry.enabled
  name: docker-registry
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.5.0
- alias: gcactivities
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: gcpods
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: gcpreviews
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: controllerbuild
  condition: jenkins-x-platform.controllerbuild.enabled,controllerbuild.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: controllerrole
  condition: jenkins-x-platform.controllerrole.enabled,controllerrole.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: controllerworkflow
  condition: jenkins-x-platform.controllerworkflow.enabled,controllerworkflow.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: controllerteam
  condition: jenkins-x-platform.controllerteam.enabled,controllerteam.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: controllercommitstatus
  condition: jenkins-x-platform.controllercommitstatus.enabled,controllercommitstatus.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
- alias: postinstalljob
  condition: jenkins-x-platform.postinstalljob.enabled,postinstalljob.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.372
